### ISSUE TITLE
update whole object

### ISSUE THREAD

**Issue by naivefun** [erikolson186/zangodb#10]
I notice that there is no `save` method, does that mean the best way to do `save` with existing object is to `delete` first then `insert`?

Now the API is not easy to implement `upsert`. I need `findOne` first then if the `id` is found, in order to update I have to call `update` which will filter the collection again, which is kind of slow in large collection.

**Comment by erikolson186** [comment]
You can use the `update` method:

```javascript
col.update({ _id: doc._id }, doc, (error) => {
    if (error) { throw error; }
});
```

**Comment by naivefun** [comment]
Thanks. So is it correct that if the doc is not found (deleted by other operation), a `not found` error will be thrown?

**Comment by erikolson186** [comment]
(Deleted my previous answer so you wouldn't see it before it was updated to reflect your edit.)

You can use the `update` method, and either pass the entire object or only what needs to be updated (recommended).

An error should not be thrown if nothing could be updated.

I will look into implementing `upsert`. Thank you for the recommendation!
