### ISSUE TITLE
query on nested object path 

### ISSUE THREAD

**Issue by OpsSingular** [erikolson186/zangodb#13]
Nice library... keep up the good work

I have a question, while the below is supported 

`col.find({ x: 4, g: { $lt: 10 } }, { k: 0 })`

Will querying on nested objects path be supported too like in mongo

`col.find({ 'person.age' : { $lt: 10 } })`

**Comment by erikolson186** [comment]
Thank you for the compliment.

Querying nested objects using a path works. I just tested your sample query and it worked. 

Here is the code I used for testing:

```javascript
const db = new zango.Db(Math.random(), ['col']);
const col = db.collection('col');

const docs = [
    { person: { age: 30 } },
    { person: { age: 8 } }
];

col.insert(docs).then(() => {
    return col.find({
        'person.age': { $lt: 10 }
    }).forEach(doc => console.log('doc:', doc));                      
}).catch(error => console.error(error));
```

The output was the following:

```
doc: { person: { age: 8 }, _id: 2 }
```

**Comment by OpsSingular** [comment]
Hey Thanks for the quick reply... it works!! i can also confirm that pushing object to deep nested arrays works too..

it would be great if zango supports listening to the changes (out of box) to the collection in future. This helps build an eventstore in indexedDB which can be used to sync, updates to collections, with Mongodb. This usecase would be ideal for offline apps. Thanks again.

**Comment by erikolson186** [comment]
I'm glad it works.

I think I'm going to add support for change events. I initially was opposed to it (see issue https://github.com/erikolson186/zangodb/issues/8), however the usefulness seems to outweigh the negatives.
