### ISSUE TITLE
is $pull supported?

### ISSUE THREAD

**Issue by OpsSingular** [erikolson186/zangodb#14]
Hi Again,

Just curious if $pull is supported. I have requirement to pull/remove items from an nested array. Is there a way to do so?

**Comment by erikolson186** [comment]
Currently the following update operators are supported: `$set`, `$unset`, `$rename`, `$inc`, `$mul`, `$min`, `$max`, `$push`, and `$pop`, but not `$pull`. I will look into implementing `$pull` for the next version.

**Comment by OpsSingular** [comment]
Is there a way to achieve the same result using a combination of supported operators... I have tried unset but it just clears the value... may be combing unset with pop?...wanted to know your views on this as i am looking hard to solve this last hurdle.

Thanks for the help so far. Cheers

**Comment by erikolson186** [comment]
Not with the supported update operators. 

I have a question for you. Do you require filter operator support for `$pull`? 

That is, do you require usage such as:

```javascript
col.update({}, { $pull: { values: { $gt: 4 } } });
```

Or instead, using `$pull` with a value:

```javascript
col.update({}, { $pull: { values: 8 } });
```

Which of these examples is closer to your required functionality?

**Comment by OpsSingular** [comment]
Pull with a value

**Comment by erikolson186** [comment]
OK, I have an implementation written. I need to write some unit tests then I will publish a new version of ZangoDB with basic `$pull` support.

**Comment by OpsSingular** [comment]
Wow.. that was quick.. let me know once you are done

**Comment by erikolson186** [comment]
Done. I went ahead and also implemented the `$pullAll` and `$addToSet` update operators while I was at it.

**Comment by OpsSingular** [comment]
Fantastic!!! Will try them out today. Thanks 😊

**Comment by OpsSingular** [comment]
Hi, 

i upgraded to 1.0.5 but i am not able to get the query to work...couldn't understand what is that i am doing wrong..my code below

      inspections.update({ _id: this.inspectionId }, {
        $pull: { 'Insp.Oper.Operative.0.Tests.Com.0.Questions':
        { Question: this.questionSection } },
      }, (error) => {
        if (error) {
          console.log(error); // eslint-disable-line
        }
      });

I have verified the path and the value for this.questionSection is exists in the array not as a direct array item but as a value to a property...

**Comment by erikolson186** [comment]
I tested your update with some sample data, and I was not able to reproduce the error.  Something might be up with the `_id` you are using. Did you test that the document exists with the `_id`?

Here is the code I used for testing:

```javascript
const db = new zango.Db(Math.random(), ['inspections']);
const inspections = db.collection('inspections');

const inspection_id = 38;
const question_selection = { x: 4 };

const docs = [
    {
        _id: inspection_id,
        
        Insp: {
            Oper: {
                Operative: [
                    {
                        Tests: {
                            Com: [
                                {
                                    Questions: [
                                        { Question: { x: 3 } },
                                        { Question: question_selection }
                                    ]
                                }
                            ]
                        }
                    }
                ]
            }
        }
    }
];

const getQuestions = (doc) => {
    return doc.Insp.Oper.Operative[0].Tests.Com[0].Questions;
};

inspections.insert(docs).then(() => {
    return inspections.findOne({ _id: inspection_id }, (error, doc) => {
        console.log('before:', getQuestions(doc));
    }); 
}).then(() => {
    return inspections.update({ _id: inspection_id }, {
        $pull: {
            'Insp.Oper.Operative.0.Tests.Com.0.Questions':
            { Question: question_selection }
        },
    });
}).then(() => {
    return inspections.findOne({ _id: inspection_id }, (error, doc) => {
        console.log('after:', getQuestions(doc));
    });
}).catch(error => console.error(error));
```

**Comment by OpsSingular** [comment]
Hi,

I am not able to get this to work. I have testing if the document exits and it does exist and i get the result when i use findOne query

      inspections.findOne({ _id: this.inspectionId, 'Insp.Oper.Operative.0.Tests.Com.0.Questions':
      { $elemMatch: { 'Question': 'i am a question?' } } }).then((result) => {
        console.log(result); // eslint-disable-line
      });

Strange indeed!!

**Comment by OpsSingular** [comment]
I have done some additional testing... This time i have hardcoded the values and pulling value from first array but the value still persists in the indexeddb even after running the below query

      inspections.update({ _id: '5951413977a72100b40c9a79' }, {
        $pull: {
          'Insp.Oper.Operative':
          { __ID: 202559 }, // eslint-disable-line
        },
      }, (error) => {
        if (error) {
          console.log(error); // eslint-disable-line
        } 
      });

**Comment by OpsSingular** [comment]
Hi,

To eliminate all possibilities i have checked $pull on a **different** collection but got the same result. My code is below.... i have a simple appointments collection with notes array and i wanted to pull the array item which matches note. 

      appointments.update({ _id: '59416e0b2735a63eacf7244b' }, {
        $pull: {
          notes:
          { note: "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl." }, // eslint-disable-line
        },
      }, (error) => {
        if (error) {
          console.log(error); // eslint-disable-line
        } 
      });

**Comment by OpsSingular** [comment]
Hi, I figured out the exact scenario in which $pull fails. Please see the modification i made below to your test code

      const db = new zango.Db(Math.random(), ['inspections']);
      const inspections = db.collection('inspections');

      const inspection_id = 38;
      const question_selection = { x: 'Aenean auctor gravida sem.' };

      const docs = [
          {
              _id: inspection_id,
              Insp: {
                  Oper: {
                      Operative: [
                          {
                              Tests: {
                                  Com: [
                                      {
                                          Questions: [
                                              { 
                                                Question: 
                                                  { 
                                                    x: "Aenean auctor gravida sem.",
                                                    y: "Nullam porttitor lacus at turpis.",
                                                    z: "porttitor porttitor gravida at turpis."                                                    
                                                  }
                                              },
                                              { 
                                                Question: 
                                                  { 
                                                    x: "gravida auctor gravida sem.",
                                                    y: "lacus porttitor porttitorat turpis.",
                                                    z: "turpis porttitor gravida at turpis."                                                    
                                                  }
                                              },                                              
                                          ]
                                      }
                                  ]
                              }
                          }              
                      ]
                  }
              }
          }
      ];

      const getQuestions = (doc) => {
          return doc.Insp.Oper.Operative[0].Tests.Com[0].Questions;
      };

      inspections.insert(docs).then(() => {
          return inspections.findOne({ _id: inspection_id }, (error, doc) => {
              console.log('before:', getQuestions(doc));
          }); 
      }).then(() => {
          return inspections.update({ _id: inspection_id }, {
              $pull: {
                  'Insp.Oper.Operative.0.Tests.Com.0.Questions':
                  { Question: question_selection }
              },
          });
      }).then(() => {
          return inspections.findOne({ _id: inspection_id }, (error, doc) => {
              console.log('after:', getQuestions(doc));
          });
      }).catch(error => console.error(error));  

$pull works if i remove y and z from Question object.

Thanks for your time

**Comment by erikolson186** [comment]
I just tested your update with MongoDB and it doesn't work either. With MongoDB and ZangoDB, the entire question object must be provided to `$pull`.

With my test code, the following change is required:

```javascript
const question_selection = {
    x: 'Aenean auctor gravida sem.',
    y: 'Nullam porttitor lacus at turpis.',
    z: 'porttitor porttitor gravida at turpis.'
};
```

I tried to find a MongoDB usage of `$pull` that would get around this, such as by using `$elemMatch`, but I couldn't find anything that worked.

**Comment by OpsSingular** [comment]
Thanks for your tip.. I am now providing the entire object and pulling the matching object from the array. Works fine now :-)
