### ISSUE TITLE
aggregate ignores order of sort and skip

### ISSUE THREAD

**Issue by MajorBass** [erikolson186/zangodb#15]
Mongodb `aggregate` follows the order specified in pipeline. But zangodb does not appear to. I think that I must be missing something. Following is an adapted example from issue #9 :

```
var db = new zango.Db(Math.random(), { col: ['x', 'g'] });
var col = db.collection('col');
var docs = [{ x: 2, g: 3 }, { x: 2, g: 8 }, { x: 2, g: 8, z: 10 }, { x: 3, z: 3, g: 4 }, { x: 4, k: 8, g: 1 }, { x: 6, g: 9 }, { x: 10, k: 4 }, { x: undefined }, { x: null }, { x: [{ k: 2 }, { k: 8 }] }];
col.insert(docs);

col.aggregate([{$skip : 2}, {$sort: {g: -1} }, ]).toArray().then(docs => {
  console.log(docs.map(doc => doc.g))
});

col.aggregate([{$sort: {g: -1} }, {$skip : 2}]).toArray().then(docs => {
  console.log(docs.map(doc => doc.g))
});
```

Output in both cases is:

```
(8) [undefined, undefined, undefined, undefined, 9, 8, 4, 1]
```

What is the correct way to query a collection, sort it and then use skip and limit? I am trying to do this to paginate ordered data.

Many thanks for this wonderful library. With its help, using IndexedDB has been a joy!

**Comment by erikolson186** [comment]
Thank you for pointing this out. Your sample code should work. There appears to be a bug introduced in version 1.0.2 (commit https://github.com/erikolson186/zangodb/commit/9ec68da0aac158523e53a129262328b23b0e2df1). I will look into it.

**Comment by erikolson186** [comment]
Update: I found the culprit, which requires a small change to fix. There is something else I am also looking into, and once finished I will publish an update. Thanks.

**Comment by MajorBass** [comment]
Thanks for the update! :heart:

**Comment by erikolson186** [comment]
I published the update. If you would try it out, I would appreciate it.

**Comment by MajorBass** [comment]
Just tried it out and it works! Thank you for awesome support :)

**Comment by MajorBass** [comment]
One off topic question, if I have a  question about using a few functions, where should i ask?

**Comment by erikolson186** [comment]
You could make an issue and optionally apply the question label. Alternatively you could email me, just look at my profile page for my address.

**Comment by erikolson186** [comment]
You could make an issue and optionally apply the question label. Alternatively you could email me, just look at my profile page for my address.
