### ISSUE TITLE
Relation between size of docs and insert speed

### ISSUE THREAD

**Issue by bildsoe** [erikolson186/zangodb#16]
Hello, 

Thank you for a great framework.

I have a question. Have you done any benchmarking on inserts. I'm trying to figure out the optimal size for the docs array, when inserting into a collection using:

collection.insert(docs).then(function () { ... });

Or rather i'm trying to figure out if I need to split the array into chunks.

BR
Thomas

**Comment by erikolson186** [comment]
Bulk inserts use a single transaction which improves the performance over inserting documents individually. A downside is that active read-write transactions, which insertion uses, must terminate before any queries are processed.

I performed some benchmarking with inserting 10,000 small documents. With a batch size of 1000 I found a good balance between performance and stability. Greater than that and oddly the performance dropped. Lower than that and issues started to arise with the large number of transactions. When the batch size was 50 or lower, the performance dropped. This was done with Firefox. Results may vary.

**Comment by bildsoe** [comment]
I've done some benchmarking now as well.

I'm inserting documents consisting of a key (an url) and a blob containing around 5kb image data.

promises.push({
    url: urlString,
    data: blobData
});

I'm inserting a total of approx. 4200 documents. I've split then into chunks of 1,2,5,10,20... documents. And then I insert them syncronously (i finish a chunk before starting the next).

1 doc chunks: ~45000ms
5 doc chunks: ~19000ms
10 doc chunks: ~15000ms
20 doc chunks: ~14000ms
50 doc chunks: ~13000ms
100 doc chunks: ~12000ms
500 doc chunks: ~12000ms
1000 doc chunks: ~12000ms

When I run all of it async, I get the MAX_WRITE_OPERATIONS_PER_MINUTE runtime error.

BR
Thomas

**Comment by erikolson186** [comment]
Your data seems to resemble mine, with a batch size of 1000 documents looking like a good option if database access is not important until all documents are inserted. 

Regarding the MAX_WRITE_OPERATIONS_PER_MINUTE error, this seems to only affect Chrome? I found the following page, but it doesn't mention IndexedDB: https://developer.chrome.com/extensions/storage

**Comment by erikolson186** [comment]
Your data seems to resemble mine, with a batch size of 1000 documents looking like a good option if database access is not important until all documents are inserted. 

Regarding the MAX_WRITE_OPERATIONS_PER_MINUTE error, this seems to only affect Chrome? I found the following page, but it doesn't mention IndexedDB: https://developer.chrome.com/extensions/storage

**Comment by bildsoe** [comment]
Yes, I found that as well. But I don't experience it consistently, so for now I'm just going to "waterfall" each chunk. With approx. 4 chunks, that shouldn't be a problem.

Thanks for replying.
