### ISSUE TITLE
Operator similar to LIKE in SQL

### ISSUE THREAD

**Issue by MajorBass** [erikolson186/zangodb#18]
Is it possible to have something similar to LIKE operator in SQL? Mongo supports regex.

Either way, would love to know your thoughts on this. This is useful when writing queries that search for keywords in documents.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by erikolson186** [comment]
Thank you for the suggestion.

I have been considering adding support for regular expressions. MongoDB supports expressions compatible with PCRE version 8.39 and JavaScript. Adding compatibility for PCRE to ZangoDB is a concern. However, PCRE appears to be a superset of JavaScript compatible regular expressions.

As of now, the only option I am familiar with is to manually filter the documents using regular expressions or other means.

**Comment by MajorBass** [comment]
Using native JavaScript regex can work. This is what will be used for most working in JS land. Let me know if it makes sense.

**Comment by erikolson186** [comment]
It makes sense. It is a good idea. I will go ahead and start implementing it when I am available to. Thank you.

**Comment by MajorBass** [comment]
Let me know if you need a hand. I am not aware of the internal design, but can take a stab at it if you can point in the right direction.

**Comment by MajorBass** [comment]
@erikolson186 Sorry to bug you... but it will be great if you could give some pointers. Thank you!

**Comment by erikolson186** [comment]
Sorry, I have been busy. The `$regex` implementation is almost good to go, it just needs support for `$options`. Then some unit tests. 

If you are curious about how filter operators are implemented, take a look at [filter.js](https://github.com/erikolson186/zangodb/blob/master/src/lang/filter.js).

**Comment by erikolson186** [comment]
OK, I pushed the update: https://github.com/erikolson186/zangodb/commit/868babfbd493af2ac058194855587263e86e5bf9

**Comment by MajorBass** [comment]
I will take it for a test drive soon. Thank you so much!

**Comment by MajorBass** [comment]
Tested and confirmed to work fine!
