### ISSUE TITLE
Bower would be awesome

### ISSUE THREAD

**Issue by KodingSykosis** [erikolson186/zangodb#2]
Any chance you'd add this to bower?
https://bower.io/

**Comment by erikolson186** [comment]
I just looked into it and I am not so sure. It seems that using npm, unpkg, browserify, webpack, etc, is more popular and convenient than Bower. Is there a benefit for using Bower? Thanks.

**Comment by erikolson186** [comment]
I went ahead and added it to bower. If you would try it out, that would be great:

`bower install zangodb`
