### ISSUE TITLE
ZangoDB does not create IndexedDB collection 

### ISSUE THREAD

**Issue by GasimGasimzada** [erikolson186/zangodb#3]
I have the following code:

db.js

    import zango from 'zangodb';

    const db = new zango.Db('app', {
      translations: ['id'],
      services: ['id', 'key'],
      console: true
    });

    export default db;

logger.js

    import db from 'environment/db';

    class Logger {

      static log(message, type) {
        db.collection('console').insert({
          timestamp: 'test',
          message,
          type
        }, (error) => {
          if (error) {
            throw error;
          }
          console.log('success');
        });
      }

    }

    export default Logger;

test.js

    import Logger from 'environment/logger';

    Logger.log('test log', 'info');

I keep getting the following error:

> NotFoundError (DOM IDBDatabase Exception 8): Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

My other two collections (services and translations) work properly but for some reason the 3rd one does not run. What am I missing here?

**Comment by erikolson186** [comment]
I was not able to reproduce the error. I compiled your code with Babel and Browserify, and ran it with Firefox, Chrome, and Edge, and was displayed "success" in the console for each. I also added some extra code to insert into the other collections for testing. I checked to make sure the data was being inserted into all three collections.

It seems like a strange bug to only affect that collection. What browser and platform did you experience this bug with? Have you tried other browsers? If you use the storage inspector with your web browser, do you see the "console" collection? Are you running any other code along with what you posted?
