### ISSUE TITLE
$regex is supposed to be supported but is not

### ISSUE THREAD

**Issue by oliverfriedmann** [erikolson186/zangodb#31]
Using it in a query like {value: {$regex: /abc/}} throws Error: unknown operator '$regex'

**Comment by oliverfriedmann** [comment]
Seems like it is working, just not published on NPM.

**Comment by wideweide** [comment]
how to make npm' version ok?
or how to import zangodb.min.js?

**Comment by wideweide** [comment]
got it :
npm i git+https://github.com/erikolson186/zangodb.git

**Comment by delcon** [comment]
$regex still is not published to npm
and 
npm i git+https://github.com/erikolson186/zangodb.git
throws error on loading
