### ISSUE TITLE
add change listener to collection?

### ISSUE THREAD

**Issue by naivefun** [erikolson186/zangodb#8]
It would be great if there is:
```
collection.on('change', e => ...);
```
or other events like `creation` `delete` ...

**Comment by erikolson186** [comment]
It would be nice. There is a problem though: IndexedDB does not emit events for changes to object stores (collections) yet allows for multiple connections to a given database. This means that the events you proposed could not be ensured to be emitted for changes across connections.

I would instead recommend emitting these events in your own code. This way certain assumptions could be made regarding how your own databases are used.
